apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 1024Mi
      cpu: "600m"
    defaultRequest:
      memory: 512Mi
      cpu: "300m"
    max:
      memory: 2Gi
      cpu: "800m"
    min:
      memory: 256Mi
      cpu: "100m"
    type: Container