---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-cms-deployment
spec:
  selector:
    matchLabels:
      app: admin-cms 
  replicas: 3
  template:
    metadata:
      labels:
        app: admin-cms 
        limitType: low
    spec:
      containers:
        - name: admin-cms
          image: openim/admin_cms:v2.3.8
          imagePullPolicy: Always 
          ports:
            - containerPort: 10200
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
            - name: USUAL_CONFIG_NAME
              value: "/Open-IM-Server"
          resources:
            requests:
              memory: "256Mi"
              cpu: 150m
            limits:
              memory: "512Mi"
              cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-usualconfig
      affinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - admin-cms 
            topologyKey: kubernetes.io/hostname

  strategy: #更新策略
    type: RollingUpdate # 滚动更新