---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-cms-deployment
spec:
  selector:
    matchLabels:
      app: admin-cms 
  replicas: 3
  template:
    metadata:
      labels:
        app: admin-cms 
    spec:
      containers:
        - name: admin-cms
          image: openim/admin_cms:v2.3.8
          imagePullPolicy: Always 
          ports:
            - containerPort: 10200
              name: admin-cms-port
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
            - name: USUAL_CONFIG_NAME
              value: "/Open-IM-Server"
          resources:
            requests:
              memory: "256Mi"
              cpu: 150m
            limits:
              memory: "512Mi"
              cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-usualconfig
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - admin-cms 
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate 
---
apiVersion: v1
kind: Service
metadata:
  name: admin-cms
spec:
  ports:
    - name: admin-cms-svc-port
      protocol: TCP
      port: 10200
      targetPort: admin-cms-port
  selector:
    app: admin-cms 
  type: ClusterIP  