---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-deployment
spec:
  selector:
    matchLabels:
      app: office
  replicas: 2
  template:
    metadata:
      labels:
        app: office 
    spec:
      containers:
      - name: office
        image: openim/office:v2.3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 10210
          name: office-port
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
          - name: USUAL_CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "256Mi"
            cpu: 150m
          limits:
            memory: "512Mi"
            cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-usualconfig
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - office
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: office
spec:
  ports:
    - name: office-svc-port
      protocol: TCP
      port: 10210
      targetPort: office-port
  selector:
    app: office
  type: ClusterIP  
