apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-data-sc
provisioner: cluster.local/nfs-subdir-external-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  server: 192.168.1.243
  path: "/k8s/storage/nfs/mongo"
volumeBindingMode: Immediate
