---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api-deployment
spec:
  selector:
    matchLabels:
      app: cms-api
  replicas: 3
  template:
    metadata:
      labels:
        app: cms-api
    spec:
      containers:
      - name: cms-api
        image: openim/cms_api:v2.3.8
        imagePullPolicy: Always
        ports:
        - containerPort: 10006
          name: cms-api-port
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"
          - name: USUAL_CONFIG_NAME
            value: "/Open-IM-Server"
        resources:
          requests:
            memory: "256Mi"
            cpu: 150m
          limits:
            memory: "512Mi"
            cpu: 300m
      volumes:
        - name: config
          projected:
            sources:
            - configMap:
                name: openim-config
            - configMap:
                name: openim-usualconfig
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cms-api
              topologyKey: kubernetes.io/hostname
  strategy: 
    type: RollingUpdate 
---
apiVersion: v1
kind: Service
metadata:
  name: cms-api
spec:
  ports:
    - name: cms-api-svc-port
      protocol: TCP
      port: 10006
      targetPort: cms-api-port
  selector:
    app: cms-api
  type: ClusterIP  