apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-pv
  namespace: redis
spec:
    capacity:
      storage: 10Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: "redis-data-sc"
    nfs:
      path: "/k8s/storage/nfs/redis"
      server: 192.168.1.243